import { useEffect, useState } from 'react'
import EmptyState from '../components/common/EmptyState'
import { useLoading } from '../hooks/useLoading'
import { hrService, type PayrollItem } from '../services/hrService'
import PayrollCard from '../components/PayrollCard'
import Badge from '../components/common/Badge'

export default function Payroll(): JSX.Element {
  const [items, setItems] = useState<PayrollItem[]>([])
  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const { withLoading } = useLoading()

  useEffect(() => {
    let active = true

    async function load(): Promise<void> {
      try {
        setLoading(true)
        const data = await withLoading(() => hrService.payroll())
        if (active) setItems(data || [])
      } catch (err: unknown) {
        if (active) setError(err instanceof Error ? err.message : 'Failed to load payroll')
      } finally {
        if (active) setLoading(false)
      }
    }

    void load()
    return () => { active = false }
  }, [])

  return (
    <div className="page-stack">
      <div className="page-heading">
        <div>
          <p className="eyebrow">Finance</p>
          <h2>My Salary Statements</h2>
          <p className="muted">Review your monthly earnings, bonuses, and deductions.</p>
        </div>
        {loading && <Badge tone="warning">Refreshing</Badge>}
      </div>

      {error && (
        <div className="alert alert-error" style={{ marginBottom: '20px' }}>
          {error}
        </div>
      )}

      {loading && items.length === 0 ? (
        <div className="loading-state" style={{ padding: '60px', textAlign: 'center' }}>
          <p className="muted">Fetching your statements...</p>
        </div>
      ) : items.length > 0 ? (
        <div className="grid grid-2">
          {items.map((item) => (
            <PayrollCard key={item.id} item={item} />
          ))}
        </div>
      ) : (
        <div style={{ padding: '40px' }}>
          <EmptyState 
            title="No payroll records found"
            description="Your monthly salary statements will appear here once generated by the HR Admin."
          />
        </div>
      )}
    </div>
  )
}